###########################################################################
######################                                                #####
###############         ADVANCE BACKPACK MAKE BY LIGHTMAXVN        ########
########                                                         ##########
#####     |Version: 1.0.0                                    ##############
###       |SupportVersion: 1.12-1.16.4                  ###################
##                                                 ########################
###########################################################################

# MySQL configuration
mysql:
  tableName: advanceBackPack
  host: localhost
  port: 3306
  database: backpack
  username: root
  password:
  useSSL: false
