############################################################################
###################                                                    #####
################         ADVANCE BACKPACK MAKE BY LIGHTMAXVN        ########
###########                                                       ##########
########     |Version: 1.0.0                                  ##############
######       |SupportVersion: 1.12-1.16.4                ###################
####                                                ########################
############################################################################

# MySQL configuration
mysql:
  enable: true
  tableName: advanceBackPack
  host: localhost
  port: 3306
  database: backpack
  username: root
  password:
  useSSL: false

#Nếu MySQL được bật thì dòng dưới này không có tác dụng!
EnableYAMLStorage: false #you dont have to care this, just ignore or u can turn it on

##################################################################
#           AdvanceBackPack.use.<amount>                         #
#      <amount> is number backpack layer can use. For example    #
#      - AdvanceBackPack.use.3 equal player can use 3 backpacks  #
##################################################################